import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { Filter, Phone, RefreshCw, Search } from "lucide-react";
import { getWarrantyTracker, getWarrantyTrackerCounts, getWarrantyTrackerFilterOptions } from "../services/warrantyTrackerApi";

const views=["ALL_ACTIVE","ACTION_REQUIRED","FOLLOW_UP_DUE","VISIT_OVERDUE","DOCUMENTS_PENDING","COMPLAINT_NOT_REGISTERED","VISIT_PENDING","AWAITING_RESULT","REPLACEMENT_PENDING","READY_TO_DELIVER","AWAITING_CUSTOMER_DECISION","REJECTED","RESOLVED","CLOSED"];
const label=value=>value?value.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,letter=>letter.toUpperCase()):"—";
const empty={FOLLOW_UP_DUE:"No follow-ups due",VISIT_OVERDUE:"No overdue visits",DOCUMENTS_PENDING:"No missing required documents",ALL_ACTIVE:"No active warranty cases"};
function Select({title,value="",values=[],onChange}){return <label className="text-sm font-bold">{title}<select value={value} onChange={event=>onChange(event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border bg-white px-2"><option value="">All</option>{values?.map(item=><option key={item} value={item}>{label(item)}</option>)}</select></label>}
function Cell({main="—",sub,danger}){return <td className={`p-3 ${danger?"font-bold text-red-700":""}`}><div>{main||"—"}</div>{sub&&<small className="text-slate-500">{sub}</small>}</td>}

export default function WarrantyTracker(){
 const navigate=useNavigate(),[url,setUrl]=useSearchParams(),[page,setPage]=useState(null),[counts,setCounts]=useState({}),[options,setOptions]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[filtersOpen,setFiltersOpen]=useState(false),[search,setSearch]=useState(url.get("search")||"");
 const params=useMemo(()=>Object.fromEntries(url.entries()),[url]);
 const update=changes=>{const next=new URLSearchParams(url);Object.entries(changes).forEach(([key,value])=>value===null||value===""?next.delete(key):next.set(key,String(value)));setUrl(next);};
 useEffect(()=>{const timer=setTimeout(()=>{if(search!==(url.get("search")||""))update({search,page:null});},350);return()=>clearTimeout(timer);},[search]); // eslint-disable-line react-hooks/exhaustive-deps
 const load=useCallback(async signal=>{setLoading(true);setError("");try{const[list,nextCounts]=await Promise.all([getWarrantyTracker(params,signal),getWarrantyTrackerCounts(params,signal)]);setPage(list);setCounts(nextCounts);}catch(nextError){if(nextError.name!=="AbortError")setError(nextError.message);}finally{if(!signal?.aborted)setLoading(false);}},[params]);
 useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>load(controller.signal),0);return()=>{clearTimeout(timer);controller.abort();};},[load]);
 useEffect(()=>{const controller=new AbortController();getWarrantyTrackerFilterOptions(controller.signal).then(setOptions).catch(()=>{});return()=>controller.abort();},[]);
 useEffect(()=>{const focus=()=>load();window.addEventListener("focus",focus);return()=>window.removeEventListener("focus",focus);},[load]);
 const view=params.view||"ALL_ACTIVE",rows=page?.content||[],reset=()=>{setSearch("");setUrl(new URLSearchParams({view:"ALL_ACTIVE"}));};
 return <main id="main-content" className="mx-auto w-full max-w-7xl p-3 pb-24 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-2"><div><h1 className="text-2xl font-extrabold text-blue-950">Warranty Tracker</h1><p className="text-sm font-semibold text-slate-500">Operational warranty work and follow-ups</p></div><button onClick={()=>load()} className="flex min-h-10 items-center gap-2 rounded-xl border px-3 font-bold"><RefreshCw size={17}/>Refresh</button></div>
  <div className="mt-4 flex gap-2 overflow-x-auto pb-2">{views.map(item=><button key={item} onClick={()=>update({view:item,page:null})} className={`shrink-0 rounded-full px-3 py-2 text-sm font-bold ${view===item?"bg-blue-950 text-white":"bg-slate-100 text-blue-950"}`}>{label(item)} <span className="opacity-75">{counts[item]??"—"}</span></button>)}</div>
  <div className="mt-3 flex gap-2"><label className="relative flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input value={search} onChange={event=>setSearch(event.target.value)} maxLength={120} placeholder="Ticket, customer, mobile, serial, manufacturer..." className="min-h-11 w-full rounded-xl border pl-10 pr-3"/></label><button onClick={()=>setFiltersOpen(value=>!value)} className="flex min-h-11 items-center gap-2 rounded-xl border px-3 font-bold"><Filter size={18}/>Filters</button></div>
  {filtersOpen&&<div className="mt-3 grid gap-3 rounded-xl bg-slate-50 p-3 sm:grid-cols-4"><Select title="Manufacturer" value={params.manufacturer} values={options?.manufacturers} onChange={value=>update({manufacturer:value,page:null})}/><Select title="State" value={params.state} values={options?.warrantyStates} onChange={value=>update({state:value,page:null})}/><Select title="Result" value={params.result} values={options?.warrantyResults} onChange={value=>update({result:value,page:null})}/><Select title="Pending Action" value={params.pendingAction} values={options?.pendingActions} onChange={value=>update({pendingAction:value,page:null})}/><Select title="Sort" value={params.sort||"MOST_OVERDUE"} values={["MOST_OVERDUE","OLDEST_CLAIM","NEWEST_CLAIM","FOLLOW_UP_DATE","EXPECTED_VISIT_DATE","LAST_UPDATED","DAYS_PENDING","TICKET_NUMBER","MANUFACTURER"]} onChange={value=>update({sort:value,page:null})}/><label className="text-sm font-bold">Follow-up from<input type="date" value={params.followUpFrom||""} onChange={event=>update({followUpFrom:event.target.value,page:null})} className="mt-1 min-h-11 w-full rounded-xl border px-2"/></label><label className="text-sm font-bold">Follow-up to<input type="date" value={params.followUpTo||""} onChange={event=>update({followUpTo:event.target.value,page:null})} className="mt-1 min-h-11 w-full rounded-xl border px-2"/></label><button onClick={reset} className="min-h-10 rounded-xl border font-bold text-red-700">Clear all</button></div>}
  {error&&<div className="mt-4 rounded-xl bg-red-50 p-4 text-red-800"><b>{error}</b><button onClick={()=>load()} className="ml-3 underline">Retry</button></div>}{loading&&!page&&<div className="mt-4 h-24 animate-pulse rounded-xl bg-slate-100"/>}{!loading&&!error&&rows.length===0&&<div className="mt-6 rounded-xl bg-slate-50 p-8 text-center"><p className="font-extrabold text-blue-950">{empty[view]||"No cases match these filters"}</p><button onClick={reset} className="mt-2 font-bold text-blue-800 underline">Reset filters</button></div>}
  {rows.length>0&&<><div className="mt-4 hidden overflow-x-auto rounded-xl border bg-white sm:block"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr>{["Ticket","Customer","Product","Manufacturer","Warranty State","Pending Action","Due / Overdue","Days Pending","Last Updated"].map(item=><th key={item} className="p-3">{item}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.claimId} onClick={()=>navigate(`/tickets/${row.ticketId}#warranty`)} className="cursor-pointer border-t hover:bg-blue-50"><Cell main={row.ticketNumber} sub={row.ticketStatus}/><Cell main={row.customerName} sub={row.mobileNumber}/><Cell main={row.productType} sub={row.replacementSerial||row.originalSerial}/><Cell main={row.manufacturer}/><Cell main={label(row.state)} sub={label(row.result)}/><Cell main={row.pendingAction?.label}/><Cell main={row.pendingAction?.overdue?`Overdue ${row.pendingAction.daysOverdue}d`:row.pendingAction?.dueDate||"—"} danger={row.pendingAction?.overdue}/><Cell main={`${row.daysPending} days`}/><Cell main={row.lastWarrantyActivityAt?new Date(row.lastWarrantyActivityAt).toLocaleDateString("en-IN"):"—"}/></tr>)}</tbody></table></div><div className="mt-4 space-y-3 sm:hidden">{rows.map(row=><article key={row.claimId} className="rounded-xl border bg-white p-4"><div className="flex justify-between"><b className="text-blue-950">{row.ticketNumber}</b><span className="text-xs font-bold">{row.daysPending} days</span></div><p className="font-bold">{row.customerName} · {row.productType}</p><p className="text-sm text-slate-600">{row.manufacturer||"Manufacturer not set"}</p><div className={`mt-2 rounded-lg p-2 text-sm font-bold ${row.pendingAction?.overdue?"bg-red-50 text-red-800":"bg-blue-50 text-blue-900"}`}>{row.pendingAction?.label||"No immediate action"}</div><details className="mt-2 text-sm"><summary className="font-bold">More details</summary><p>Complaint: {row.complaintNumber||"Not registered"}</p><p>Follow-up: {row.nextFollowUpDate||"Not scheduled"}</p><p>Documents missing: {row.requiredDocumentsMissingCount}</p></details><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>navigate(`/tickets/${row.ticketId}#warranty`)} className="min-h-10 rounded-xl bg-blue-950 font-bold text-white">Open Ticket</button><a href={`tel:${row.mobileNumber}`} className="flex min-h-10 items-center justify-center gap-1 rounded-xl border font-bold"><Phone size={16}/>Call</a></div></article>)}</div><div className="mt-4 flex items-center justify-between"><button disabled={page.first||loading} onClick={()=>update({page:page.page-1})} className="min-h-10 rounded-xl border px-4 font-bold disabled:opacity-40">Previous</button><span className="text-sm font-bold">Page {page.page+1} of {Math.max(1,page.totalPages)}</span><button disabled={page.last||loading} onClick={()=>update({page:page.page+1})} className="min-h-10 rounded-xl border px-4 font-bold disabled:opacity-40">Next</button></div></>}</main>;
}
