import { useEffect, useRef } from "react";
import { X } from "lucide-react";

export default function WarrantyDialog({open,title,description,onClose,children,variant="drawer",destructive=false,closeDisabled=false}){
 const panel=useRef(null),closeRef=useRef(null),titleId="warranty-dialog-title",descriptionId="warranty-dialog-description";
 useEffect(()=>{if(!open)return;const previous=document.activeElement;document.body.style.overflow="hidden";closeRef.current?.focus();const key=event=>{if(event.key==="Escape"&&!closeDisabled)onClose();if(event.key==="Tab"&&panel.current){const list=[...panel.current.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')];if(!list.length)return;const first=list[0],last=list[list.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}};document.addEventListener("keydown",key);return()=>{document.body.style.overflow="";document.removeEventListener("keydown",key);previous?.focus?.();};},[open,onClose,closeDisabled]);
 if(!open)return null;
 const drawer=variant==="drawer";
 return <div className={`fixed inset-0 z-[80] flex bg-slate-950/40 ${drawer?"justify-end":"items-end justify-center p-3 sm:items-center"}`} role="dialog" aria-modal="true" aria-labelledby={titleId} aria-describedby={description?descriptionId:undefined}><button type="button" className={drawer?"hidden flex-1 sm:block":"absolute inset-0"} onClick={closeDisabled?undefined:onClose} aria-label="Close dialog"/><section ref={panel} className={drawer?"relative flex h-full w-full flex-col bg-white shadow-2xl sm:w-[36rem] sm:max-w-[90vw]":"relative w-full max-w-md rounded-2xl bg-white p-4 shadow-2xl"}><header className={drawer?"sticky top-0 z-10 flex items-start justify-between gap-3 border-b bg-white px-4 py-4":"flex items-start justify-between gap-3"}><div><p className={`text-xs font-extrabold uppercase ${destructive?"text-red-700":"text-amber-700"}`}>{destructive?"Important confirmation":"Warranty action"}</p><h2 id={titleId} className="mt-1 text-lg font-extrabold text-blue-950">{title}</h2>{description&&<p id={descriptionId} className="mt-1 text-sm font-semibold text-slate-600">{description}</p>}</div><button ref={closeRef} type="button" onClick={onClose} disabled={closeDisabled} className="flex min-h-11 min-w-11 items-center justify-center rounded-xl border disabled:opacity-40" aria-label="Close dialog"><X aria-hidden="true"/></button></header><div className={drawer?"min-h-0 flex-1 overflow-y-auto overscroll-contain px-4 py-4 pb-[max(1rem,env(safe-area-inset-bottom))]":"mt-4"}>{children}</div></section></div>;
}
