import { useEffect, useRef, useState } from "react";
import { Camera, Eye, FileUp, Trash2 } from "lucide-react";
import { deactivateWarrantyAttachment, fetchWarrantyAttachmentBlob, getWarrantyAttachments, getWarrantyDocumentSummary, supersedeWarrantyAttachment, uploadWarrantyAttachment } from "../../services/warrantyApi";

const categories=["BILL_IMAGE","WARRANTY_CARD_IMAGE","PRODUCT_IMAGE","PRODUCT_SERIAL_NUMBER_IMAGE","MANUFACTURER_SERVICE_SLIP","OTHER_WARRANTY_DOCUMENT","REPLACEMENT_PROOF","REPLACEMENT_PRODUCT_IMAGE","REPLACEMENT_SERIAL_NUMBER_IMAGE","REPLACEMENT_WARRANTY_CARD_IMAGE","OTHER_REPLACEMENT_DOCUMENT"];
const labels={BILL_IMAGE:"Purchase Bill",WARRANTY_CARD_IMAGE:"Warranty Card",PRODUCT_IMAGE:"Original Product Image",PRODUCT_SERIAL_NUMBER_IMAGE:"Product Serial Number",MANUFACTURER_SERVICE_SLIP:"Manufacturer Service Slip",OTHER_WARRANTY_DOCUMENT:"Other Warranty Document",REPLACEMENT_PROOF:"Replacement Proof",REPLACEMENT_PRODUCT_IMAGE:"Replacement Product",REPLACEMENT_SERIAL_NUMBER_IMAGE:"Replacement Serial Number",REPLACEMENT_WARRANTY_CARD_IMAGE:"New Warranty Card",OTHER_REPLACEMENT_DOCUMENT:"Other Replacement Document"};
const replacementCategory=category=>category.startsWith("REPLACEMENT_")||category==="OTHER_REPLACEMENT_DOCUMENT";
const size=n=>n<1048576?`${Math.ceil(n/1024)} KB`:`${(n/1048576).toFixed(1)} MB`;
async function compress(file){if(!file.type.startsWith("image/")||file.type==="image/webp"||file.size<1200000)return file;const bitmap=await createImageBitmap(file),scale=Math.min(1,1800/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/jpeg",.82));bitmap.close();if(!blob)throw new Error("Could not compress this image. Choose a smaller file.");return new File([blob],file.name.replace(/\.[^.]+$/,".jpg"),{type:"image/jpeg"});}

export default function WarrantyDocuments({ticketId,claim,canManage,onChanged,onError,initialCategory}){
 const[items,setItems]=useState([]),[summary,setSummary]=useState(null),[category,setCategory]=useState(initialCategory||"BILL_IMAGE"),[file,setFile]=useState(null),[preview,setPreview]=useState(""),[progress,setProgress]=useState(0),[busy,setBusy]=useState(false),[replaceReason,setReplaceReason]=useState(""),[removeTarget,setRemoveTarget]=useState(null),[removeReason,setRemoveReason]=useState("");
 const gallery=useRef(null),camera=useRef(null);
 const load=async()=>{const[attachments,nextSummary]=await Promise.all([getWarrantyAttachments(ticketId,claim.id),getWarrantyDocumentSummary(ticketId,claim.id)]);setItems(attachments||[]);setSummary(nextSummary);};
 useEffect(()=>{let live=true;Promise.all([getWarrantyAttachments(ticketId,claim.id),getWarrantyDocumentSummary(ticketId,claim.id)]).then(([attachments,nextSummary])=>{if(live){setItems(attachments||[]);setSummary(nextSummary);}}).catch(error=>{if(live)onError(error.message);});return()=>{live=false;};},[ticketId,claim.id,onError]);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
 const choose=async event=>{const original=event.target.files?.[0];if(!original)return;try{const next=await compress(original);if(next.size>8388608)throw new Error("File is larger than 8 MB after compression.");if(preview)URL.revokeObjectURL(preview);setFile(next);setPreview(URL.createObjectURL(next));setReplaceReason("");}catch(error){onError(error.message);}};
 const replacementId=replacementCategory(category)?claim.activeReplacement?.id:null;
 const existing=items.find(item=>item.active&&item.category===category&&(item.replacementId||null)===(replacementId||null));
 const upload=async()=>{if(!file||existing&&!replaceReason.trim())return;setBusy(true);setProgress(0);try{if(existing)await supersedeWarrantyAttachment(ticketId,claim.id,existing.id,{file,reason:replaceReason.trim(),version:existing.version},setProgress);else await uploadWarrantyAttachment(ticketId,claim.id,{category,replacementId,file},setProgress);setFile(null);setPreview("");setReplaceReason("");await load();await onChanged();}catch(error){onError(error.status===409?"This document changed while you were editing. Reload the latest documents and try again.":error.message);}finally{setBusy(false);}};
 const open=async item=>{try{const url=URL.createObjectURL(await fetchWarrantyAttachmentBlob(item.contentPath));window.open(url,"_blank","noopener,noreferrer");window.setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(error){onError(error.message);}};
 const remove=async()=>{if(!removeTarget||!removeReason.trim())return;setBusy(true);try{await deactivateWarrantyAttachment(ticketId,claim.id,removeTarget.id,removeReason.trim(),removeTarget.version);setRemoveTarget(null);setRemoveReason("");await load();await onChanged();}catch(error){onError(error.status===409?"This document changed while you were editing. Reload the latest documents and try again.":error.message);}finally{setBusy(false);}};
 const current=items.filter(item=>item.active),history=items.filter(item=>!item.active);
 return <div><div className="flex items-center justify-between gap-2"><p className="text-sm font-extrabold text-blue-950">Warranty Documents</p><span className="rounded-full bg-amber-100 px-2 py-1 text-xs font-bold">{summary?.requiredMissingCount||0} required missing</span></div><div className="mt-2 grid gap-2 sm:grid-cols-2">{(summary?.requirements||[]).map(requirement=><div key={requirement.category} className="rounded-xl bg-slate-50 p-2 text-sm"><b>{labels[requirement.category]}</b><p className={requirement.present?"text-emerald-700":"text-slate-500"}>{requirement.present?"Available":requirement.required?"Required — missing":"Recommended — missing"}{requirement.overridden?" · override recorded":""}</p></div>)}</div>
  {current.map(item=><div key={item.id} className="mt-2 flex items-center justify-between gap-2 rounded-xl border border-cyan-100 p-3 text-sm"><div className="min-w-0"><b>{labels[item.category]}</b><p className="truncate">{item.displayFilename} · {size(item.sizeBytes)}</p><small>{item.uploadedByEmployeeName||item.uploadedByEmployeeId}</small></div><div className="flex"><button type="button" onClick={()=>open(item)} className="flex min-h-11 min-w-11 items-center justify-center" aria-label={`View ${labels[item.category]}`}><Eye size={18}/></button>{canManage&&claim.active&&<button type="button" onClick={()=>{setRemoveTarget(item);setRemoveReason("");}} className="flex min-h-11 min-w-11 items-center justify-center text-red-700" aria-label={`Remove ${labels[item.category]}`}><Trash2 size={18}/></button>}</div></div>)}
  {removeTarget&&<section className="mt-3 rounded-xl border border-red-200 bg-red-50 p-3" aria-labelledby="remove-document-title"><h3 id="remove-document-title" className="font-extrabold text-red-900">Remove {labels[removeTarget.category]}?</h3><p className="mt-1 text-sm font-semibold text-red-800">It remains available in audit history.</p><label className="mt-3 block text-sm font-bold text-red-900">Reason<textarea value={removeReason} onChange={event=>setRemoveReason(event.target.value)} rows={3} className="mt-1 w-full rounded-xl border border-red-200 bg-white p-3"/></label><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={()=>setRemoveTarget(null)} className="min-h-11 rounded-xl border bg-white font-bold">Cancel</button><button type="button" onClick={remove} disabled={busy||!removeReason.trim()} className="min-h-11 rounded-xl bg-red-700 font-bold text-white disabled:opacity-50">Remove document</button></div></section>}
  {canManage&&claim.active&&<section className="mt-3 rounded-xl bg-cyan-50 p-3"><h3 className="text-sm font-extrabold">Add warranty document</h3><label className="mt-3 block text-sm font-bold">Document type<select value={category} onChange={event=>{setCategory(event.target.value);setFile(null);setReplaceReason("");}} className="mt-1 min-h-11 w-full rounded-xl border bg-white px-3">{categories.filter(value=>!replacementCategory(value)||claim.activeReplacement).map(value=><option key={value} value={value}>{labels[value]}</option>)}</select></label><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={()=>camera.current.click()} className="flex min-h-11 items-center justify-center gap-2 rounded-xl border bg-white"><Camera size={18}/>Take photo</button><button type="button" onClick={()=>gallery.current.click()} className="flex min-h-11 items-center justify-center gap-2 rounded-xl border bg-white"><FileUp size={18}/>Choose file</button></div><input hidden ref={camera} type="file" accept="image/*" capture="environment" onChange={choose}/><input hidden ref={gallery} type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={choose}/>{file&&<div className="mt-3 rounded-xl bg-white p-3 text-sm"><b>{file.name} · {size(file.size)}</b>{file.type.startsWith("image/")&&<img src={preview} alt="Selected document preview" className="mt-2 max-h-64 w-full object-contain"/>}{existing&&<><p className="mt-3 font-bold text-amber-900">This replaces the current {labels[category]}. The old file remains in history.</p><label className="mt-2 block font-bold">Replacement reason<textarea value={replaceReason} onChange={event=>setReplaceReason(event.target.value)} rows={3} className="mt-1 w-full rounded-xl border p-3"/></label></>}<button type="button" onClick={upload} disabled={busy||Boolean(existing&&!replaceReason.trim())} className="ke-primary-action mt-3 min-h-11 w-full rounded-xl font-bold disabled:opacity-50">{busy?`Uploading ${progress}%`:existing?"Replace document":"Upload document"}</button></div>}</section>}
  {history.length>0&&<details className="mt-3"><summary className="min-h-11 cursor-pointer py-2 text-sm font-extrabold">Document History ({history.length})</summary>{history.map(item=><div key={item.id} className="mt-2 rounded-xl bg-slate-100 p-3 text-sm"><b>{labels[item.category]} · Historical</b><p>{item.displayFilename}{item.deactivationReason?` · ${item.deactivationReason}`:""}</p><button type="button" onClick={()=>open(item)} className="min-h-10 font-bold text-blue-900">View retained document</button></div>)}</details>}</div>;
}
