import { useCallback, useEffect, useState } from "react";
import { ChevronDown, ChevronUp, ShieldCheck } from "lucide-react";
import { hasAccess } from "../../utils/access";
import { createWarranty, getAssignableEmployees, getWarranty, getWarrantyEvents, updateWarranty } from "../../services/warrantyApi";

const emptyForm = { billingDate:"",warrantyStartDate:"",warrantyEndDate:"",manufacturerName:"",productSerialNumber:"",modelNumber:"",manufacturerComplaintNumber:"",complaintRegisteredDate:"",expectedVisitDate:"",manufacturerEngineerName:"",manufacturerEngineerMobile:"",manufacturerServiceCenterName:"",warrantyNotes:"",nextFollowUpDate:"",warrantyOwnerEmployeeId:"",state:"DETAILS_REQUIRED" };
const label = (value) => value ? value.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,(c)=>c.toUpperCase()) : "Not provided";
const dateTime = (value) => value ? new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)) : "Not provided";
const formFrom = (claim) => Object.fromEntries(Object.keys(emptyForm).map((key)=>[key,key==="warrantyOwnerEmployeeId"?(claim?.warrantyOwner?.employeeId||""):(claim?.[key]||"")]));

function Field({labelText,name,value,onChange,type="text",disabled=false,children}) {
 return <label className="block text-sm font-bold text-slate-700">{labelText}{children||<input name={name} type={type} value={value} onChange={onChange} disabled={disabled} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-300 px-3 py-2 text-base outline-none focus:border-blue-950 disabled:bg-slate-100"/>}</label>;
}

export default function WarrantySection({ ticketId }) {
 const canView=hasAccess("VIEW_WARRANTY"),canManage=hasAccess("MANAGE_WARRANTY"),canAssign=hasAccess("ASSIGN_TICKET");
 const [claim,setClaim]=useState(null),[loading,setLoading]=useState(canView),[error,setError]=useState(""),[editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[form,setForm]=useState(emptyForm),[events,setEvents]=useState([]),[employees,setEmployees]=useState([]);
 const load=useCallback(async()=>{if(!canView)return;setLoading(true);setError("");try{const data=await getWarranty(ticketId);setClaim(data);setForm(formFrom(data));if(data){const history=await getWarrantyEvents(ticketId,data.id);setEvents(history?.events||[]);}}catch(e){setError(e.message||"Unable to load warranty details.");}finally{setLoading(false);}},[canView,ticketId]);
 useEffect(()=>{const timer=window.setTimeout(()=>{load();},0);return()=>window.clearTimeout(timer);},[load]);
 useEffect(()=>{if(editing&&canAssign&&employees.length===0)getAssignableEmployees().then((data)=>setEmployees(Array.isArray(data)?data:[])).catch(()=>setEmployees([]));},[editing,canAssign,employees.length]);
 if(!canView&&!canManage)return null;
 const change=(e)=>setForm((current)=>({...current,[e.target.name]:e.target.value}));
 const mark=async()=>{if(saving||!window.confirm("Mark this existing repair ticket as under warranty? No separate ticket will be created."))return;setSaving(true);setError("");try{const data=await createWarranty(ticketId,{});setClaim(data);setForm(formFrom(data));if(canView)await load();}catch(e){setError(e.status===409?"An active warranty claim already exists. Refresh to see the latest details.":e.message);}finally{setSaving(false);}};
 const save=async()=>{if(saving)return;setSaving(true);setError("");try{const body={version:claim.version};Object.keys(emptyForm).forEach((key)=>{if(key!=="warrantyOwnerEmployeeId"||canAssign)body[key]=form[key]||null;});const data=await updateWarranty(ticketId,claim.id,body);setClaim(data);setForm(formFrom(data));setEditing(false);if(canView)await load();}catch(e){setError(e.status===409?"This warranty case was updated by another user. Refresh and review the latest details before saving again.":e.message);}finally{setSaving(false);}};
 return <section className="rounded-2xl border border-amber-200 bg-white p-3.5 shadow-sm">
  <div className="flex items-center justify-between gap-3"><h2 className="flex items-center gap-2 text-lg font-extrabold text-blue-950"><ShieldCheck size={20}/> Warranty</h2>{claim&&canManage&&<button type="button" onClick={()=>setEditing((v)=>!v)} className="inline-flex min-h-10 items-center gap-1 rounded-xl border border-blue-200 px-3 text-sm font-bold text-blue-950">{editing?"Close":"Edit"}{editing?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</button>}</div>
  {loading&&<p className="mt-3 rounded-xl bg-blue-50 px-3 py-2 text-sm font-semibold text-slate-600">Loading warranty details...</p>}
  {error&&<p className="mt-3 rounded-xl bg-red-50 px-3 py-2 text-sm font-semibold text-red-700">{error}</p>}
  {!loading&&!claim&&<div className="mt-3"><p className="text-sm font-semibold text-slate-600">This ticket has not been marked as warranty.</p>{canManage&&<button type="button" onClick={mark} disabled={saving} className="ke-accent-action mt-3 min-h-11 w-full rounded-xl px-4 text-sm font-bold disabled:opacity-60">{saving?"Marking...":"Mark In Warranty"}</button>}</div>}
  {claim&&<>
   <div className="mt-3 grid grid-cols-2 gap-2 text-sm"><div className="rounded-xl bg-amber-50 p-3"><p className="font-semibold text-slate-500">State</p><p className="mt-1 font-extrabold text-blue-950">{label(claim.state)}</p></div><div className="rounded-xl bg-amber-50 p-3"><p className="font-semibold text-slate-500">Result</p><p className="mt-1 font-extrabold text-blue-950">{label(claim.result)}</p></div></div>
   <dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="font-semibold text-slate-500">Manufacturer</dt><dd className="font-bold text-slate-800">{claim.manufacturerName||"Not provided"}</dd></div><div><dt className="font-semibold text-slate-500">Serial / Model</dt><dd className="font-bold text-slate-800">{claim.productSerialNumber||claim.modelNumber||"Not provided"}</dd></div><div><dt className="font-semibold text-slate-500">Warranty Owner</dt><dd className="font-bold text-slate-800">{claim.warrantyOwner?.employeeName||claim.warrantyOwner?.employeeId||"Not assigned"}</dd></div><div><dt className="font-semibold text-slate-500">Next Follow-up</dt><dd className="font-bold text-slate-800">{claim.nextFollowUpDate||"Not provided"}</dd></div></dl>
   <div className={`mt-3 rounded-xl px-3 py-2 text-sm ${claim.pendingAction?.blocking?"bg-red-50 text-red-800":"bg-blue-50 text-blue-900"}`}><p className="font-semibold">Next pending action</p><p className="font-extrabold">{claim.pendingAction?.label||"No immediate action"}</p></div>
   {editing&&<div className="mt-4 space-y-4 border-t border-amber-100 pt-4">
    <fieldset className="grid gap-3 sm:grid-cols-3"><legend className="mb-2 text-sm font-extrabold uppercase text-slate-500">Warranty basics</legend><Field labelText="Billing Date" name="billingDate" type="date" value={form.billingDate} onChange={change}/><Field labelText="Start Date" name="warrantyStartDate" type="date" value={form.warrantyStartDate} onChange={change}/><Field labelText="End Date" name="warrantyEndDate" type="date" value={form.warrantyEndDate} onChange={change}/><Field labelText="Warranty State" name="state" value={form.state} onChange={change}><select name="state" value={form.state} onChange={change} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3"><option value="DETAILS_REQUIRED">Details Required</option><option value="COMPLAINT_REQUIRED">Complaint Required</option><option value="VISIT_PENDING">Visit Pending</option><option value="AWAITING_RESULT">Awaiting Result</option><option value="CLOSED">Closed</option></select></Field><div className="text-sm"><p className="font-bold text-slate-700">Warranty Result</p><p className="mt-1.5 min-h-11 rounded-xl bg-slate-100 px-3 py-3 font-semibold text-slate-700">{label(claim.result)} (read-only)</p></div></fieldset>
    <fieldset className="grid gap-3 sm:grid-cols-3"><legend className="mb-2 text-sm font-extrabold uppercase text-slate-500">Product identification</legend><Field labelText="Manufacturer" name="manufacturerName" value={form.manufacturerName} onChange={change}/><Field labelText="Serial Number" name="productSerialNumber" value={form.productSerialNumber} onChange={change}/><Field labelText="Model Number" name="modelNumber" value={form.modelNumber} onChange={change}/></fieldset>
    <fieldset className="grid gap-3 sm:grid-cols-2"><legend className="mb-2 text-sm font-extrabold uppercase text-slate-500">Manufacturer complaint</legend><Field labelText="Complaint Number" name="manufacturerComplaintNumber" value={form.manufacturerComplaintNumber} onChange={change}/><Field labelText="Registered Date" name="complaintRegisteredDate" type="date" value={form.complaintRegisteredDate} onChange={change}/><Field labelText="Service Center" name="manufacturerServiceCenterName" value={form.manufacturerServiceCenterName} onChange={change}/><Field labelText="Engineer Name" name="manufacturerEngineerName" value={form.manufacturerEngineerName} onChange={change}/><Field labelText="Engineer Mobile" name="manufacturerEngineerMobile" value={form.manufacturerEngineerMobile} onChange={change}/></fieldset>
    <fieldset className="grid gap-3 sm:grid-cols-3"><legend className="mb-2 text-sm font-extrabold uppercase text-slate-500">Visit and follow-up</legend><Field labelText="Expected Visit" name="expectedVisitDate" type="date" value={form.expectedVisitDate} onChange={change}/><Field labelText="Next Follow-up" name="nextFollowUpDate" type="date" value={form.nextFollowUpDate} onChange={change}/><Field labelText="Warranty Owner" name="warrantyOwnerEmployeeId" value={form.warrantyOwnerEmployeeId} onChange={change} disabled={!canAssign}>{canAssign?<select name="warrantyOwnerEmployeeId" value={form.warrantyOwnerEmployeeId} onChange={change} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3"><option value="">Not assigned</option>{employees.map((e)=><option key={e.employeeId} value={e.employeeId}>{e.name} ({e.employeeId})</option>)}</select>:null}</Field></fieldset>
    <label className="block text-sm font-bold text-slate-700">Notes<textarea name="warrantyNotes" value={form.warrantyNotes} onChange={change} maxLength={2000} rows={3} className="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2 text-base"/></label>
    <div className="grid grid-cols-2 gap-2"><button type="button" onClick={()=>{setEditing(false);setForm(formFrom(claim));}} disabled={saving} className="min-h-11 rounded-xl border border-blue-950 font-bold text-blue-950">Cancel</button><button type="button" onClick={save} disabled={saving} className="ke-primary-action min-h-11 rounded-xl font-bold disabled:opacity-60">{saving?"Saving...":"Save Warranty"}</button></div>
   </div>}
   {events.length>0&&<details className="mt-4 border-t border-amber-100 pt-3"><summary className="cursor-pointer text-sm font-extrabold text-blue-950">Recent warranty activity</summary><div className="mt-2 space-y-2">{events.map((event)=><div key={event.id} className="rounded-xl bg-slate-50 px-3 py-2 text-sm"><p className="font-bold text-slate-800">{event.summary}</p><p className="text-xs font-semibold text-slate-500">{event.actorNameSnapshot||event.actorEmployeeId} • {dateTime(event.eventTimestamp)}</p></div>)}</div></details>}
  </>}
 </section>;
}
