import { useEffect, useRef, useState } from "react";
import { ChevronLeft, ChevronRight, Clock3 } from "lucide-react";
import { getWarrantyEvents } from "../../services/warrantyApi";
import { formatDateTime } from "./warrantyPresentation";

export default function WarrantyRecentActivity({ticketId,claimId,refreshToken=0}){
 const root=useRef(null),[data,setData]=useState(null),[visible,setVisible]=useState(false),[full,setFull]=useState(false),[page,setPage]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState("");
 useEffect(()=>{const node=root.current;if(!node)return;const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting))setVisible(true);},{rootMargin:"240px"});observer.observe(node);return()=>observer.disconnect();},[]);
 useEffect(()=>{if(!visible)return;const controller=new AbortController();const timer=window.setTimeout(()=>{setLoading(true);setError("");getWarrantyEvents(ticketId,claimId,full?page:0,full?20:5,controller.signal).then(setData).catch(e=>{if(e.name!=="AbortError")setError(e.message);}).finally(()=>setLoading(false));},0);return()=>{window.clearTimeout(timer);controller.abort();};},[visible,full,page,ticketId,claimId,refreshToken]);
 return <section ref={root} className="rounded-xl border border-slate-200 bg-white p-3" aria-labelledby="warranty-activity-title"><div className="flex items-center justify-between gap-3"><h3 id="warranty-activity-title" className="flex items-center gap-2 text-sm font-extrabold text-blue-950"><Clock3 size={17} aria-hidden="true"/>{full?"Warranty History":"Recent Activity"}</h3>{data?.totalElements>5&&<button type="button" onClick={()=>{setFull(v=>!v);setPage(0);}} className="min-h-10 text-sm font-extrabold text-blue-900">{full?"Show recent":"View full history"}</button>}</div>{loading&&<p className="mt-3 text-sm font-semibold text-slate-500" role="status">Loading warranty activity…</p>}{error&&<p className="mt-3 rounded-lg bg-red-50 p-2 text-sm font-bold text-red-700">{error}</p>}{!loading&&data?.events?.length===0&&<p className="mt-3 text-sm font-semibold text-slate-500">No warranty activity yet.</p>}<div className="mt-2 space-y-2">{data?.events?.map(event=><article key={event.id} className="rounded-lg bg-slate-50 p-2 text-sm"><p className="font-bold text-slate-800">{event.summary}</p><p className="mt-1 text-xs font-semibold text-slate-500">{event.actorNameSnapshot||event.actorEmployeeId||"System"} · {formatDateTime(event.eventTimestamp)}</p></article>)}</div>{full&&data?.totalPages>1&&<nav className="mt-3 flex items-center justify-between" aria-label="Warranty history pages"><button type="button" disabled={data.first} onClick={()=>setPage(p=>p-1)} className="flex min-h-10 items-center rounded-lg border px-2 text-sm font-bold disabled:opacity-40"><ChevronLeft size={17}/>Previous</button><span className="text-xs font-bold text-slate-600">Page {data.page+1} of {data.totalPages}</span><button type="button" disabled={data.last} onClick={()=>setPage(p=>p+1)} className="flex min-h-10 items-center rounded-lg border px-2 text-sm font-bold disabled:opacity-40">Next<ChevronRight size={17}/></button></nav>}</section>;
}
