import { useEffect, useState } from "react";
import { getWarrantyReplacements, markReplacementDelivered, moveReplacementToReadyDelivery, recordWarrantyReplacement, supersedeWarrantyReplacement, updateWarrantyReplacement } from "../../services/warrantyApi";
const today=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Kolkata"});
const blank={replacementReceivedDate:today(),newProductName:"",newProductType:"",newModelNumber:"",newSerialNumber:"",newWarrantyStartDate:"",newWarrantyEndDate:"",replacementReferenceNumber:"",replacementProvidedBy:"",replacementNotes:"",serialNumberOverrideReason:"",referenceOverrideReason:"",supersedeReason:""};
const value=(v)=>v||""; const display=(v)=>v||"Not provided";
function Input({label,name,type="text",form,onChange,required=false}){return <label className="block text-sm font-bold text-slate-700">{label}<input name={name} type={type} value={form[name]} onChange={onChange} required={required} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3 text-base"/></label>}
function fields(r={}){return {...blank,replacementReceivedDate:value(r.replacementReceivedDate)||today(),newProductName:value(r.newProductName),newProductType:value(r.newProductType),newModelNumber:value(r.newModelNumber),newSerialNumber:value(r.newSerialNumber),newWarrantyStartDate:value(r.newWarrantyStartDate),newWarrantyEndDate:value(r.newWarrantyEndDate),replacementReferenceNumber:value(r.replacementReferenceNumber),replacementProvidedBy:value(r.replacementProvidedBy),replacementNotes:value(r.replacementNotes),serialNumberOverrideReason:value(r.serialNumberOverrideReason),referenceOverrideReason:value(r.referenceOverrideReason)};}
export default function WarrantyReplacementActions({ticketId,claim,onUpdated,onError}){
 const active=claim.activeReplacement,[history,setHistory]=useState([]),[mode,setMode]=useState(""),[form,setForm]=useState(blank),[saving,setSaving]=useState(false);
 const load=async()=>{try{setHistory(await getWarrantyReplacements(ticketId,claim.id)||[]);}catch(e){onError(e.message);}};
 useEffect(()=>{let cancelled=false;if(active)getWarrantyReplacements(ticketId,claim.id).then((data)=>{if(!cancelled)setHistory(data||[]);}).catch((e)=>{if(!cancelled)onError(e.message);});return()=>{cancelled=true;};},[active,claim.id,ticketId,onError]);
 const change=(e)=>setForm((f)=>({...f,[e.target.name]:e.target.value}));
 const open=(next)=>{setMode(next);setForm(next==="record"?blank:{...fields(active),supersedeReason:""});};
 const payload=()=>({replacementReceivedDate:form.replacementReceivedDate,newProductName:form.newProductName||null,newProductType:form.newProductType||null,newModelNumber:form.newModelNumber||null,newSerialNumber:form.newSerialNumber||null,newWarrantyStartDate:form.newWarrantyStartDate||null,newWarrantyEndDate:form.newWarrantyEndDate||null,replacementReferenceNumber:form.replacementReferenceNumber||null,replacementProvidedBy:form.replacementProvidedBy,replacementNotes:form.replacementNotes||null,serialNumberOverrideReason:form.serialNumberOverrideReason||null,referenceOverrideReason:form.referenceOverrideReason||null,claimVersion:claim.version,replacementVersion:active?.version});
 const submit=async(e)=>{e.preventDefault();setSaving(true);onError("");try{let data;if(mode==="record")data=await recordWarrantyReplacement(ticketId,claim.id,payload());if(mode==="edit")data=await updateWarrantyReplacement(ticketId,claim.id,active.id,payload());if(mode==="supersede")data=await supersedeWarrantyReplacement(ticketId,claim.id,active.id,{supersedeReason:form.supersedeReason,claimVersion:claim.version,currentReplacementVersion:active.version,replacement:{...payload(),replacementVersion:null}});setMode("");await onUpdated(data);await load();}catch(e2){onError(e2.status===409?e2.message||"Replacement was updated by another user. Refresh and try again.":e2.message);}finally{setSaving(false);}};
 const move=async()=>{if(!window.confirm("Move this replacement ticket using the configured Ready Delivery workflow?"))return;setSaving(true);onError("");try{await onUpdated(await moveReplacementToReadyDelivery(ticketId,claim.id,{version:claim.version}));}catch(e){onError(e.message);}finally{setSaving(false);}};
 const delivered=async()=>{if(!window.confirm("Confirm the ticket has already been delivered through the ticket workflow and close this warranty claim?"))return;setSaving(true);onError("");try{await onUpdated(await markReplacementDelivered(ticketId,claim.id,{deliveredDate:today(),claimVersion:claim.version,replacementVersion:active.version}));}catch(e){onError(e.status===409?"Deliver the ticket through its existing delivery workflow first, then confirm replacement delivery here.":e.message);}finally{setSaving(false);}};
 return <div className="mt-4 border-t border-emerald-100 pt-3">
  {claim.state==="REPLACEMENT_APPROVED_AWAITING_PRODUCT"&&!active&&<button type="button" onClick={()=>open("record")} className="min-h-11 rounded-xl border border-emerald-300 px-3 text-sm font-extrabold text-emerald-900">Record Replacement Received</button>}
  {active&&<div className="rounded-xl bg-emerald-50 p-3"><p className="text-sm font-extrabold text-emerald-950">Replacement Product <span className="font-semibold text-emerald-700">• received by shop</span></p><dl className="mt-2 grid grid-cols-2 gap-2 text-sm"><div><dt className="font-semibold text-slate-500">Product / Model</dt><dd className="font-bold">{display(active.newProductName||active.newProductType)}{active.newModelNumber?` • ${active.newModelNumber}`:""}</dd></div><div><dt className="font-semibold text-slate-500">Serial</dt><dd className="font-bold">{active.newSerialNumber||"Missing — override recorded"}</dd></div><div><dt className="font-semibold text-slate-500">Received</dt><dd className="font-bold">{active.replacementReceivedDate}</dd></div><div><dt className="font-semibold text-slate-500">Reference / Provider</dt><dd className="font-bold">{display(active.replacementReferenceNumber)} • {active.replacementProvidedBy}</dd></div><div><dt className="font-semibold text-slate-500">New warranty</dt><dd className="font-bold">{active.newWarrantyStartDate||"Not issued"}{active.newWarrantyEndDate?` to ${active.newWarrantyEndDate}`:""}</dd></div><div><dt className="font-semibold text-slate-500">Customer delivery</dt><dd className="font-bold">{active.replacementGivenToCustomerDate||"Not yet delivered"}</dd></div></dl></div>}
  {active&&claim.active&&<div className="mt-2 flex flex-wrap gap-2"><button onClick={()=>open("edit")} className="min-h-10 rounded-xl border border-emerald-200 px-3 text-sm font-bold">Edit Details</button><button onClick={()=>open("supersede")} className="min-h-10 rounded-xl border border-emerald-200 px-3 text-sm font-bold">Supersede Replacement</button>{claim.pendingAction?.code==="MOVE_REPLACEMENT_TO_READY_DELIVERY"&&<button onClick={move} disabled={saving} className="min-h-10 rounded-xl border border-violet-300 px-3 text-sm font-bold text-violet-900">Move To Ready Delivery</button>}{claim.state==="DELIVERY_PENDING"&&<button onClick={delivered} disabled={saving} className="min-h-10 rounded-xl border border-violet-300 px-3 text-sm font-bold text-violet-900">Confirm Given To Customer</button>}</div>}
  {mode&&<form onSubmit={submit} className="mt-3 grid gap-3 rounded-xl border border-emerald-100 p-3 sm:grid-cols-2"><p className="sm:col-span-2 text-sm font-extrabold text-emerald-950">{mode==="record"?"Record replacement received":mode==="edit"?"Edit non-identity replacement details":"Supersede with corrected replacement"}</p>{mode==="supersede"&&<Input label="Supersede Reason" name="supersedeReason" form={form} onChange={change} required/>}<Input label="New Product Name" name="newProductName" form={form} onChange={change}/><Input label="New Product Type" name="newProductType" form={form} onChange={change}/><Input label="New Model Number" name="newModelNumber" form={form} onChange={change}/><Input label="New Serial Number" name="newSerialNumber" form={form} onChange={change}/><Input label="Serial Override Reason" name="serialNumberOverrideReason" form={form} onChange={change}/><Input label="Replacement Received Date" name="replacementReceivedDate" type="date" form={form} onChange={change} required/><Input label="Replacement Reference Number" name="replacementReferenceNumber" form={form} onChange={change}/><Input label="Reference Override Reason" name="referenceOverrideReason" form={form} onChange={change}/><Input label="Replacement Provided By" name="replacementProvidedBy" form={form} onChange={change} required/><Input label="New Warranty Start" name="newWarrantyStartDate" type="date" form={form} onChange={change}/><Input label="New Warranty End" name="newWarrantyEndDate" type="date" form={form} onChange={change}/><label className="sm:col-span-2 text-sm font-bold text-slate-700">Replacement Notes<textarea name="replacementNotes" value={form.replacementNotes} onChange={change} maxLength={2000} rows={3} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2"/></label><div className="grid grid-cols-2 gap-2 sm:col-span-2"><button type="button" onClick={()=>setMode("")} className="min-h-11 rounded-xl border border-blue-950 font-bold">Cancel</button><button disabled={saving} className="ke-primary-action min-h-11 rounded-xl font-bold">{saving?"Saving...":"Save Replacement"}</button></div></form>}
  {history.length>1&&<details className="mt-3"><summary className="cursor-pointer text-sm font-extrabold text-blue-950">Replacement History ({history.length})</summary><div className="mt-2 space-y-2">{history.map((r)=><div key={r.id} className={`rounded-xl p-3 text-sm ${r.active?"bg-emerald-50":"bg-slate-100"}`}><p className="font-extrabold">Replacement #{r.replacementSequence} • {r.active?"Current":"Superseded"}</p><p>{display(r.newProductName||r.newProductType)}{r.newModelNumber?` • ${r.newModelNumber}`:""} • {display(r.newSerialNumber)}</p><p className="text-slate-600">Received {r.replacementReceivedDate}{r.supersedeReason?` • ${r.supersedeReason}`:""}</p></div>)}</div></details>}
 </div>;
}
