import { useState } from "react";
import { closeWarrantyClaim, markManufacturerRepairDone, markReplacementApproved, markWarrantyCustomerDidNotProceed, moveWarrantyToReadyDelivery, recordWarrantyCustomerDecision, rejectWarranty } from "../../services/warrantyApi";
const today=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Kolkata"});
const initial={date:today(),notes:"",reference:"",decision:"AWAIT_CUSTOMER_DECISION",expectedReplacementDate:"",managerOverrideReason:""};
const labels={repair:"Manufacturer Repair Done",reject:"Warranty Rejected",replacement:"Replacement Approved",didNotProceed:"Customer Did Not Proceed",customerDecision:"Record Customer Decision",moveReady:"Move To Ready Delivery",close:"Close Warranty Claim"};
function Input({label,name,value,onChange,type="text",required=false}){return <label className="block text-sm font-bold text-slate-700">{label}<input name={name} value={value} onChange={onChange} type={type} required={required} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3 text-base"/></label>}
export default function WarrantyResolutionActions({ticketId,claim,onUpdated,onError}){
 const [action,setAction]=useState(""),[form,setForm]=useState(initial),[saving,setSaving]=useState(false);const change=(e)=>setForm((v)=>({...v,[e.target.name]:e.target.value}));
 const choices=[];if(claim.state==="VISIT_COMPLETED_AWAITING_RESULT"&&claim.result==="PENDING")choices.push("repair","reject","replacement","didNotProceed");if(claim.state==="MANUFACTURER_REPAIR_COMPLETED"&&claim.result==="MANUFACTURER_REPAIR_DONE")choices.push("moveReady");if(claim.state==="WARRANTY_REJECTED_AWAITING_DECISION"&&claim.rejectionDecision==="AWAIT_CUSTOMER_DECISION")choices.push("customerDecision");if(claim.pendingAction?.code==="CLOSE_WARRANTY_CLAIM")choices.push("close");
 const immediateMove=async()=>{if(saving||!window.confirm("Move this ticket using the configured Ready Delivery workflow action?"))return;setSaving(true);onError("");try{await onUpdated(await moveWarrantyToReadyDelivery(ticketId,claim.id,{version:claim.version}));}catch(error){onError(error.status===409?"This warranty action is not configured for the ticket’s current workflow. Ask an administrator to review the workflow transition.":error.message);}finally{setSaving(false);}};
 const start=(key)=>{if(key==="moveReady"){immediateMove();return;}setAction(key);setForm({...initial,decision:key==="customerDecision"?"CONTINUE_AS_PAID_REPAIR":key==="didNotProceed"?"AWAIT_CUSTOMER_COLLECTION":"AWAIT_CUSTOMER_DECISION"});};
 const submit=async(e)=>{e.preventDefault();if(saving)return;if((action==="reject"||action==="customerDecision"||action==="didNotProceed")&&form.decision==="CONTINUE_AS_PAID_REPAIR"&&!window.confirm("This will move the ticket using the configured paid-repair workflow action. Continue?"))return;setSaving(true);onError("");try{let response;const version=claim.version;if(action==="repair")response=await markManufacturerRepairDone(ticketId,claim.id,{completionDate:form.date,completionNotes:form.notes,manufacturerReference:form.reference||null,managerOverrideReason:form.managerOverrideReason||null,version});if(action==="reject")response=await rejectWarranty(ticketId,claim.id,{rejectionDate:form.date,rejectionReason:form.notes,decision:form.decision,managerOverrideReason:form.managerOverrideReason||null,version});if(action==="replacement")response=await markReplacementApproved(ticketId,claim.id,{approvalDate:form.date,approvalReference:form.reference||null,approvalNotes:form.notes||null,expectedReplacementDate:form.expectedReplacementDate||null,version});if(action==="didNotProceed")response=await markWarrantyCustomerDidNotProceed(ticketId,claim.id,{decisionDate:form.date,reason:form.notes,ticketJourneyDecision:form.decision,version});if(action==="customerDecision")response=await recordWarrantyCustomerDecision(ticketId,claim.id,{decision:form.decision,decisionDate:form.date,decisionNotes:form.notes,version});if(action==="moveReady")response=await moveWarrantyToReadyDelivery(ticketId,claim.id,{version});if(action==="close")response=await closeWarrantyClaim(ticketId,claim.id,{version,notes:form.notes});setAction("");await onUpdated(response);}catch(error){const message=error.status===409&&/workflow|configured/i.test(error.message)?"This warranty action is not configured for the ticket’s current workflow. Ask an administrator to review the workflow transition.":error.status===409?"This warranty case was updated by another user. Refresh and review the latest details before continuing.":error.message;onError(message);}finally{setSaving(false);}};
 if(choices.length===0)return null;
 return <div className="mt-4 border-t border-violet-100 pt-3"><p className="text-sm font-extrabold text-blue-950">Warranty resolution</p><div className="mt-2 flex flex-wrap gap-2">{choices.map((key)=><button key={key} type="button" onClick={()=>start(key)} disabled={saving} className="min-h-10 rounded-xl border border-violet-200 px-3 text-sm font-bold text-violet-900">{labels[key]}</button>)}</div>
 {action&&<form onSubmit={submit} className="mt-3 grid gap-3 rounded-xl bg-violet-50 p-3 sm:grid-cols-2">{action!=="close"&&<Input label={action==="repair"?"Completion Date":action==="replacement"?"Approval Date":action==="reject"?"Rejection Date":"Decision Date"} name="date" type="date" value={form.date} onChange={change} required/>}
  {(action==="repair"||action==="replacement")&&<Input label={action==="repair"?"Manufacturer Reference":"Approval Reference"} name="reference" value={form.reference} onChange={change}/>}<Input label={action==="repair"?"Completion Notes":action==="replacement"?"Approval Notes":action==="reject"?"Rejection Reason":action==="close"?"Closure Notes":"Decision Reason / Notes"} name="notes" value={form.notes} onChange={change} required={action!=="replacement"||!form.reference}/>
  {action==="replacement"&&<Input label="Expected Replacement Date" name="expectedReplacementDate" type="date" value={form.expectedReplacementDate} onChange={change}/>} {(action==="repair"||action==="reject")&&<Input label="Manager Override Reason (if visit/complaint missing)" name="managerOverrideReason" value={form.managerOverrideReason} onChange={change}/>} 
  {action==="reject"&&<label className="text-sm font-bold text-slate-700">What happens next?<select name="decision" value={form.decision} onChange={change} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3"><option value="AWAIT_CUSTOMER_DECISION">Await customer decision</option><option value="CONTINUE_AS_PAID_REPAIR">Continue as paid repair</option><option value="CLOSE_WARRANTY_CLAIM">Close warranty claim only</option></select></label>}
  {action==="customerDecision"&&<label className="text-sm font-bold text-slate-700">Customer Decision<select name="decision" value={form.decision} onChange={change} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3"><option value="CONTINUE_AS_PAID_REPAIR">Continue as paid repair</option><option value="CLOSE_WARRANTY_CLAIM">Close warranty claim</option></select></label>}
  {action==="didNotProceed"&&<label className="text-sm font-bold text-slate-700">Repair Ticket Journey<select name="decision" value={form.decision} onChange={change} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3"><option value="AWAIT_CUSTOMER_COLLECTION">Await customer collection</option><option value="CONTINUE_AS_PAID_REPAIR">Continue as paid repair</option><option value="CLOSE_WARRANTY_CLAIM">Close warranty claim only</option></select></label>}
  <div className="grid grid-cols-2 gap-2 sm:col-span-2"><button type="button" onClick={()=>setAction("")} disabled={saving} className="min-h-11 rounded-xl border border-blue-950 font-bold text-blue-950">Cancel</button><button disabled={saving} className="ke-primary-action min-h-11 rounded-xl font-bold disabled:opacity-60">{saving?"Saving...":labels[action]}</button></div></form>}</div>;
}
