import { AlertTriangle, CalendarClock, Check, ChevronDown, Circle, FileText, ShieldCheck } from "lucide-react";
import { businessStatus, formatDate, journeyFor, pendingPresentation, RESULT_LABELS } from "./warrantyPresentation";

const tone = { COMPLETED: "border-emerald-300 bg-emerald-50 text-emerald-900", CURRENT: "border-blue-400 bg-blue-50 text-blue-950", BLOCKED: "border-red-300 bg-red-50 text-red-900", UPCOMING: "border-slate-200 bg-white text-slate-500", NOT_APPLICABLE: "border-slate-200 bg-slate-50 text-slate-500" };

const PRESENTATION_NOW=Date.now();
export function WarrantyHeader({ claim }) {
  const start = claim.markedWarrantyAt || claim.createdAt;
  const days = start ? Math.max(0, Math.floor((PRESENTATION_NOW - new Date(start).getTime()) / 86400000)) : null;
  return <header className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
    <div><p className="flex items-center gap-2 text-sm font-extrabold uppercase tracking-wide text-amber-700"><ShieldCheck size={18} aria-hidden="true"/>Warranty</p><h2 className="mt-1 text-xl font-extrabold text-blue-950">{businessStatus(claim)}</h2>{!claim.active&&<p className="mt-1 text-sm font-bold text-slate-600">Historical claim #{claim.claimSequence}</p>}</div>
    <dl className="grid gap-y-2 text-sm sm:text-right"><div><dt className="font-semibold text-slate-500">Time pending</dt><dd className="font-extrabold text-slate-800">{claim.active && days !== null ? `${days} day${days === 1 ? "" : "s"}` : "Closed"}</dd></div>{claim.pendingAction?.overdue&&<div className="text-red-700"><dt className="sr-only">Overdue</dt><dd className="font-extrabold">Overdue by {claim.pendingAction.daysOverdue} day{claim.pendingAction.daysOverdue===1?"":"s"}</dd></div>}{claim.result!=="PENDING"&&<div><dt className="font-semibold text-slate-500">Outcome</dt><dd className="font-extrabold text-slate-800">{RESULT_LABELS[claim.result] || "Recorded"}</dd></div>}</dl>
  </header>;
}

export function WarrantyPrimaryActionCard({ claim, canOpen, onOpen }) {
  const action = pendingPresentation(claim.pendingAction);
  const actionable = claim.active && action.key && canOpen(action.permission);
  return <section className={`rounded-2xl border p-4 ${claim.pendingAction?.blocking ? "border-amber-300 bg-amber-50" : claim.pendingAction?.overdue ? "border-red-200 bg-red-50" : "border-blue-200 bg-blue-50"}`} aria-labelledby="warranty-next-title">
    <p id="warranty-next-title" className="text-xs font-extrabold uppercase tracking-wide text-slate-600">What’s Next?</p><h3 className="mt-1 text-lg font-extrabold text-blue-950">{action.label}</h3><p className="mt-1 text-sm font-semibold text-slate-700">{action.description}</p>
    {claim.pendingAction?.dueDate&&<p className={`mt-2 flex items-center gap-2 text-sm font-bold ${claim.pendingAction.overdue?"text-red-700":"text-slate-700"}`}><CalendarClock size={17} aria-hidden="true"/>{claim.pendingAction.overdue?`Overdue by ${claim.pendingAction.daysOverdue} day${claim.pendingAction.daysOverdue===1?"":"s"}`:`Due ${formatDate(claim.pendingAction.dueDate)}`}</p>}
    {actionable&&<button type="button" onClick={(e)=>onOpen(action.key,{},e.currentTarget)} className="ke-primary-action mt-4 min-h-11 w-full rounded-xl px-4 text-sm font-extrabold sm:w-auto">{action.label}</button>}
    {!actionable&&action.key&&<p className="mt-3 text-sm font-bold text-slate-600">You can view this claim, but this action requires additional access.</p>}
  </section>;
}

export function WarrantyAlerts({ alerts, onOpen }) {
  if (!alerts.length) return null;
  return <section aria-labelledby="warranty-alerts-title"><h3 id="warranty-alerts-title" className="text-sm font-extrabold text-blue-950">Important Alerts</h3><div className="mt-2 space-y-2">{alerts.slice(0,2).map((a)=><div key={a.id} className={`flex items-start gap-3 rounded-xl border p-3 text-sm ${a.severity==="blocking"?"border-amber-300 bg-amber-50 text-amber-950":a.severity==="overdue"?"border-red-200 bg-red-50 text-red-800":"border-blue-100 bg-blue-50 text-blue-950"}`}><AlertTriangle className="mt-0.5 shrink-0" size={18} aria-hidden="true"/><div className="flex-1"><p className="font-bold">{a.message}</p>{a.actionKey&&<button type="button" onClick={(e)=>onOpen(a.actionKey,{category:a.category},e.currentTarget)} className="mt-2 min-h-10 rounded-lg border border-current px-3 font-extrabold">Resolve issue</button>}</div></div>)}{alerts.length>2&&<details><summary className="min-h-10 cursor-pointer py-2 text-sm font-extrabold text-blue-900">View all issues ({alerts.length})</summary><div className="space-y-2">{alerts.slice(2).map((a)=><p key={a.id} className="rounded-xl bg-slate-50 p-3 text-sm font-bold text-slate-700">{a.message}</p>)}</div></details>}</div></section>;
}

export function WarrantyJourney({ claim }) {
  return <section aria-labelledby="warranty-journey-title"><h3 id="warranty-journey-title" className="text-sm font-extrabold text-blue-950">Warranty Journey</h3><ol className="mt-2 grid gap-2 md:grid-cols-5">{journeyFor(claim).map((stage,index)=><li key={stage.label} className={`flex items-center gap-3 rounded-xl border p-3 md:block ${tone[stage.status]}`} aria-current={stage.status==="CURRENT"||stage.status==="BLOCKED"?"step":undefined}><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-current text-xs font-extrabold md:mb-2">{stage.status==="COMPLETED"?<Check size={16} aria-hidden="true"/>:stage.status==="UPCOMING"?<Circle size={12} aria-hidden="true"/>:index+1}</span><span><span className="block text-sm font-extrabold">{stage.label}</span><span className="block text-xs font-semibold">{stage.note || stage.status.replaceAll("_"," ").toLowerCase()}</span></span></li>)}</ol></section>;
}

const Row=({label,children})=>children?<div><dt className="font-semibold text-slate-500">{label}</dt><dd className="break-words font-bold text-slate-800">{children}</dd></div>:null;
export function DetailAccordion({ id, title, open, children }) { return <details open={open} className="group rounded-xl border border-slate-200 bg-white"><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between px-3 py-2 text-sm font-extrabold text-blue-950">{title}<ChevronDown size={17} className="transition group-open:rotate-180" aria-hidden="true"/></summary><div className="border-t border-slate-100 p-3" id={`warranty-${id}`}>{children}</div></details>; }
export function WarrantyDetails({ claim, currentSection }) {
  const hasComplaint=claim.manufacturerComplaintNumber||claim.complaintRegistrationAttemptDate;
  const hasVisit=claim.expectedVisitDate||claim.actualVisitDate||claim.nextFollowUpDate;
  const hasResolution=claim.result!=="PENDING"||claim.manufacturerRepairCompletionDate||claim.warrantyRejectionDate;
  const hasReplacement=claim.replacementApprovalDate||claim.activeReplacement;
  return <section aria-labelledby="warranty-details-title"><h3 id="warranty-details-title" className="mb-2 text-sm font-extrabold text-blue-950">Warranty Details</h3><div className="space-y-2">
    <DetailAccordion id="basics" title="Warranty Basics" open={currentSection==="basics"}><dl className="grid gap-3 text-sm sm:grid-cols-2"><Row label="Billing date">{formatDate(claim.billingDate)}</Row><Row label="Warranty period">{claim.warrantyStartDate?`${formatDate(claim.warrantyStartDate)}${claim.warrantyEndDate?` – ${formatDate(claim.warrantyEndDate)}`:""}`:null}</Row><Row label="Notes">{claim.warrantyNotes}</Row></dl></DetailAccordion>
    <DetailAccordion id="product" title="Product & Manufacturer"><dl className="grid gap-3 text-sm sm:grid-cols-2"><Row label="Manufacturer">{claim.manufacturerName}</Row><Row label="Serial number">{claim.productSerialNumber}</Row><Row label="Model number">{claim.modelNumber}</Row></dl></DetailAccordion>
    {hasComplaint&&<DetailAccordion id="complaint" title="Complaint Details" open={currentSection==="complaint"}><dl className="grid gap-3 text-sm sm:grid-cols-2"><Row label="Complaint number">{claim.manufacturerComplaintNumber}</Row><Row label="Registered date">{formatDate(claim.complaintRegisteredDate)}</Row><Row label="Registration attempt">{formatDate(claim.complaintRegistrationAttemptDate)}</Row><Row label="Attempt notes">{claim.complaintAttemptNotes}</Row></dl></DetailAccordion>}
    {hasVisit&&<DetailAccordion id="visit" title="Visit & Follow-up" open={currentSection==="visit"}><dl className="grid gap-3 text-sm sm:grid-cols-2"><Row label="Expected visit">{formatDate(claim.expectedVisitDate)}</Row><Row label="Actual visit">{formatDate(claim.actualVisitDate)}</Row><Row label="Engineer">{claim.manufacturerEngineerName}</Row><Row label="Engineer mobile">{claim.manufacturerEngineerMobile}</Row><Row label="Service centre">{claim.manufacturerServiceCenterName}</Row><Row label="Visit notes">{claim.visitNotes}</Row><Row label="Next follow-up">{formatDate(claim.nextFollowUpDate)}</Row><Row label="Follow-up notes">{claim.followUpNotes}</Row></dl></DetailAccordion>}
    {hasResolution&&<DetailAccordion id="resolution" title="Resolution" open={currentSection==="resolution"}><dl className="grid gap-3 text-sm sm:grid-cols-2"><Row label="Final outcome">{RESULT_LABELS[claim.result]}</Row><Row label="Repair completed">{formatDate(claim.manufacturerRepairCompletionDate)}</Row><Row label="Manufacturer reference">{claim.manufacturerRepairReference}</Row><Row label="Repair notes">{claim.manufacturerRepairCompletionNotes}</Row><Row label="Rejection date">{formatDate(claim.warrantyRejectionDate)}</Row><Row label="Rejection reason">{claim.warrantyRejectionReason}</Row><Row label="Customer decision notes">{claim.customerDecisionNotes}</Row><Row label="Closed date">{claim.claimClosedAt?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium"}).format(new Date(claim.claimClosedAt)):null}</Row></dl></DetailAccordion>}
    {hasReplacement&&<DetailAccordion id="replacement" title="Replacement" open={currentSection==="replacement"}><dl className="grid gap-3 text-sm sm:grid-cols-2"><Row label="Approved">{formatDate(claim.replacementApprovalDate)}</Row><Row label="Expected replacement">{formatDate(claim.expectedReplacementDate)}</Row><Row label="Approval reference">{claim.replacementApprovalReference}</Row><Row label="Product">{claim.activeReplacement?.newProductName||claim.activeReplacement?.newProductType}</Row><Row label="Model">{claim.activeReplacement?.newModelNumber}</Row><Row label="Serial number">{claim.activeReplacement?.newSerialNumber}</Row><Row label="Received">{formatDate(claim.activeReplacement?.replacementReceivedDate)}</Row><Row label="Provided by">{claim.activeReplacement?.replacementProvidedBy}</Row></dl></DetailAccordion>}
  </div></section>;
}

export function WarrantyDocumentsSummary({ summary, canManage, active, onOpen }) {
  if (!summary) return <section className="rounded-xl border border-slate-200 p-3" aria-live="polite"><p className="text-sm font-bold text-slate-500">Loading document summary…</p></section>;
  const total=(summary.requirements||[]).filter(r=>r.required).length,available=Math.max(0,total-summary.requiredMissingCount);
  const missing=(summary.requirements||[]).find(r=>r.required&&!r.present&&!r.overridden);
  return <section className="rounded-xl border border-cyan-100 bg-cyan-50 p-3" aria-labelledby="warranty-doc-title"><div className="flex items-center gap-2"><FileText size={18} aria-hidden="true"/><h3 id="warranty-doc-title" className="text-sm font-extrabold text-blue-950">Documents</h3></div><p className="mt-2 text-sm font-bold text-slate-800">{available} of {total} required documents available</p><p className="mt-1 text-xs font-semibold text-slate-600">{summary.requiredMissingCount} required missing · {summary.recommendedMissingCount} recommended missing</p><div className="mt-3 flex flex-wrap gap-2">{canManage&&active&&missing&&<button type="button" onClick={(e)=>onOpen("manage-documents",{category:missing.category},e.currentTarget)} className="min-h-10 rounded-lg border border-cyan-700 px-3 text-sm font-extrabold text-cyan-950">{missing.label}</button>}<button type="button" onClick={(e)=>onOpen("manage-documents",{},e.currentTarget)} className="min-h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm font-extrabold text-blue-950">View documents</button></div></section>;
}

export function WarrantyMoreActions({ groups, onOpen }) {
  const available=groups.filter(g=>g.actions.length);
  if (!available.length) return null;
  return <details className="rounded-xl border border-slate-200 bg-white"><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between px-3 py-2 text-sm font-extrabold text-blue-950">More Actions<ChevronDown size={17} aria-hidden="true"/></summary><div className="space-y-4 border-t border-slate-100 p-3">{available.map(group=><section key={group.label}><h4 className={`text-xs font-extrabold uppercase tracking-wide ${group.danger?"text-red-700":"text-slate-500"}`}>{group.label}</h4><div className="mt-2 flex flex-wrap gap-2">{group.actions.map(action=><button key={action.key} type="button" onClick={(e)=>onOpen(action.key,action.context||{},e.currentTarget)} className={`min-h-10 rounded-xl border px-3 text-sm font-bold ${action.danger?"border-red-200 text-red-800":"border-blue-200 text-blue-950"}`}>{action.label}</button>)}</div></section>)}</div></details>;
}
